### PR TITLE
Feature/carthage integration

### PR DESCRIPTION
**Pull request by petropavel13**

### CODE REVIEW

**Comment by petropavel13** [comment]
I just created cross platform XCode project inspired by this article http://basememara.com/creating-cross-platform-swift-frameworks-ios-watchos-tvos-via-carthage-cocoapods/
This project contains targets and tests for all platforms.

**Comment by Danappelxx** [comment]
Thanks for the PR! Our workflow involves the use of the Swift Package Manager to generate Xcode projects (`swift package generate-xcodeproj`) rather than having one checked in the repository. For that reason alone, I'm not sure if merging this PR is a great idea.

All that said, the [author of this library](https://github.com/bradhilton) has an iOS-ready version (with Cocoapods/Carthage support) available on his github account [here](https://github.com/bradhilton/Allegro)! I highly recommend you take a look.

**Comment by petropavel13** [comment]
Hi! Thanks for comment!
It's a good idea to use `generate-xcodeproj`. Didn't know about your workflow.

But iOS-ready version last update was 2 month ago (is Swift 3 (release version) ready? who knows..). Also, it looks like Allegro repository just copy-paste a part of code from this repo. @bradhilton, please, can you tell something about it?

There should be different solution. I know front-end platforms it's not your field of business, so I will keep my fork and close this PR.

**Comment by bradhilton** [comment]
Hi @petropavel13, `Allegro` is an older version of `Reflection` with CocoaPod support. I'm hoping to make `Reflection` available on all platforms, but that may be through another repo like `Allegro`, because `Reflection` is just for Zewo's purposes.

**Pull request closed without merging**
